Feature/sm 14 reports
spryker-middleware/report pull request #1
Opened 2018-03-22 17:03 UTC by olehokhremchuk

Please review base code and functionality for reports

2018-03-23 10:10 UTC, valerio8787 requested changes

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Business/Model/ProcessResult.php
> +     * @return mixed
Please use  TransferObject instead mixed for return type

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Business/Model/ProcessResult.php
> +     * @return mixed
see above

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Business/ReportFacade.php
> +     * @return mixed
Facade should return TO

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Business/ReportFacadeInterface.php
> +     * @return mixed
see above

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Communication/Controller/ProcessController.php
> +        $process['Process Id'] = $processResult->getIdProcess();
@olehokhremchuk Please pass $processResult TO to template as is and process it there

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Communication/Controller/ResultController.php
> +        $attributes = [];
@olehokhremchuk  See above comment about passing TO to twig, this logic is not needed in controller

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Communication/Table/ProcessResultsTable.php
> +        if ($item->getFailedItemCount() > 0) {
move html to template

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Communication/Table/ProcessesTable.php
> +        $viewDiscountUrl = Url::generate(
Please rename variable

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Persistence/Mapper/ProcessResultMapper.php
> +    public function mapArrayToStagesResult(array $stagesResults)
Pass $processResultTransfer to this method too, and use $processResultTransfer->addStageResult(stagesResultsTransfer) instead temp variable

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Persistence/ReportEntityManager.php
> +     * @return mixed
TO as return type

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Persistence/ReportEntityManagerInterface.php
> +     * @return mixed
Please change mixed to concrete type everywhere

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Persistence/ReportPersistenceFactory.php
> +    public function createProcessResultMapper()
add doc-block and return type

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Persistence/ReportPersistenceFactory.php
> +    public function getUtilEncodingService()
return type

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Persistence/ReportRepository.php
> +    public function findProcessResultByResultId(int $idResult)
use return type declaration everywhere

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/Persistence/ReportPersistenceFactory.php
> +        return SpyProcessQuery::create();
I think you should use query objects that you provide in dependency provider

2018-03-23 10:10 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Report/ReportDependencyProvider.php
> +    protected function addServiceUtilEncoding(Container $container)
use return type declaration :Container

2018-03-23 10:11 UTC, valerio8787 commented
@olehokhremchuk  Also please add declaration of required TO's from ProcessModule

2018-03-23 14:14 UTC, olehokhremchuk commented on src/SprykerMiddleware/Zed/Report/Communication/Table/ProcessResultsTable.php
> +        if ($item->getFailedItemCount() > 0) {
@valerio8787 to which template? it's an instance of AbstractTable entity. It has no template, or I should create special template for "label" component and include it to table cell someway?

2018-03-26 11:50 UTC, valerio8787 approved these changes

2018-03-26 11:51 UTC, merged